var LEVELS = [
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WCCCCCCCWFCOWOCOWOCFWFEOWOEOWOEFW',
      'WCCCCCCCWFCOWOCOWOCFWFEOWOEOWOEFW',
      'WCCCCCCCWFOOWOOOWOOFWFOOWOOOWOOFW',
      'WCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WCCCCCCCWCWCCCCCCCCCCCCCCCCCCCCCW',
      'WCCCCCCCWPWFFFFFFFFFFCFFFFCCFFFFW',
      'WWWCCCWWWFWFCEFEFEFEFFEFFFFFFCFFW',
      'WWWW WWWWFWFCEFEFEFEFEEFFFCFFFEFW',
      'W       WFWFCEFEFEFEFFEFFCFFFFFFW',
      'W       WFFFCEFFEFFEFEEEFFFFFCFFW',
      'W       WWWWWWWWWWWWWWWWWWWWWWWFW',
      'W       WFECCFFCFFFCCCFFFCFFFFFFW',
      'W       WFFCFFEFFFFFFFFFFFFFEFFCW',
      'W       WFFCFFFFFCFFFEFFCFFFFFFCW',
      'W       WXFFEFFCFFFCFFFFEFFFEFCCW',
      'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    ]
  },
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWWWWWWWWWWW',
      'WCFCFCFCFWFWFCCCCFW',
      'WCFCFCFCFWFWFFFFCFW',
      'WCFCFCFCFWPWFCCCCFW',
      'WCFCFCFCFWFWFCFFFFW',
      'WCFFCFFCFWFWFCCCCFW',
      'WWWWWWWWWWWWWWWWWWWW',
    ]
  }
];