var LEVELS = [
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WCCCCCCCWFCOWOCOWOCFWFEOWOEOWOEFW',
      'WCCCCCCCWFCOWOCOWOCFWFEOWOEOWOEFW',
      'WCCCCCCCWFOOWOOOWOOFWFOOWOOOWOOFW',
      'WCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WCCCCCCCWCWCCCCCCCCCCCCCCCCCCCCCW',
      'WCCCCCCCWPWFFFFFFFFFFCFFFFCCFFFFW',
      'WWWCCCWWWFWFCEFEFEFEFFEFFFFFFCFFW',
      'WWWW WWWWFWFCEFEFEFEFEEFFFCFFFEFW',
      'W       WFWFCEFEFEFEFFEFFCFFFFFFW',
      'W       WFFFCEFFEFFEFEEEFFFFFCFFW',
      'W       WWWWWWWWWWWWWWWWWWWWWWWFW',
      'W       WFECCFFCFFFCCCFFFCFFFFFFW',
      'W       WFFCFFEFFFFFFFFFFFFFEFFCW',
      'W       WFFCFFFFFCFFFEFFCFFFFFFCW',
      'W       WXFFEFFCFFFCFFFFEFFFEFCCW',
      'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    ]
  },
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWFFFFW',
      'WWWWWWWWWWWWCFCCXW',
      'WEFFFCFFFFFWCCWWWW',
      'WFFFWCFEEEFWFEW',
      'WFFFWCFEPEFWFCW',
      'WFFFWCFEEEFWFCW',
      'WFCFWCFFFFFWFCW',
      'WWFWWWWWWWWWFCW',
      'WCFFWCCCCC  FCW',
      'WCFFWCCCCCWWWWW',
      'WFFFWWCCCWW',
      'WFEFWWWCWWW',
      'WEFFC FFFFW',
      'WWWWW     W',
      'WEEE      W',
      'WWWWWWWWWWW',
    ]
  },
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWW',
      'WX     P  W',
      'WWWWWWWWWWW',
    ]
  },
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      "WEEEEFFFEFFFEEEEEFEEEEEEFW",
      "WEFFFFFEFEFFEFEFEFEFFFFFFW",
      "WEFEEFFEEEFFEFEFEFEEEEEEFW",
      "WEFFEFFEFEFFEFEFEFEFFFFFFW",
      "WEEEEFFEFEFFEFEFEFEEEEEEFW",
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      'W            P           W',
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WEEEFFEFFEEEFEEEFEEEFEEFFW',
      'WEFEFEFEFEFFFEFFFEFFFEFEFW',
      'WEEEFEEEFEEEFEEEFEEEFEFFEW',
      'WEFFFEFEFFFEFFFEFEFFFEFEFW',
      'WEFFFEFEFEEEFEEEFEEEFEEFFW',
      'WWWWWWWWWWWWWWWWWWWWWWWWWW'
    ]
  }
];