var LEVELS = [
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WCCCCCCCWFCOWOCOWOCFWFEOWOEOWOEFW',
      'WCCCCCCCWFCOWOCOWOCFWFEOWOEOWOEFW',
      'WCCCCCCCWFOOWOOOWOOFWFOOWOOOWOOFW',
      'WCCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WCCCCCCCWCWCCCCCCCCCCCCCCCCCCCCCW',
      'WCCCCCCCWPWFFFFFFFFFFCFFFFCCFFFFW',
      'WWWCCCWWWFWFCEFEFEFEFFEFFFFFFCFFW',
      'WWWW WWWWFWFCEFEFEFEFEEFFFCFFFEFW',
      'W       WFWFCEFEFEFEFFEFFCFFFFFFW',
      'W       WFFFCEFFEFFEFEEEFFFFFCFFW',
      'W       WWWWWWWWWWWWWWWWWWWWWWWFW',
      'W       WFECCFFCFFFCCCFFFCFFFFFFW',
      'W       WFFCFFEFFFFFFFFFFFFFEFFCW',
      'W       WFFCFFFFFCFFFEFFCFFFFFFCW',
      'W       WXFFEFFCFFFCFFFFEFFFEFCCW',
      'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    ]
  },
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWW',
      'WEFFFCFEEEW',
      'WFFFWCFEPEW',
      'WFCFWCFEEEW',
      'WWFWWWWWWWW',
      'WCFFWCCXCCW',
      'WCFFWCCCCCW',
      'WFFFWWCCCWW',
      'WFEFWWWCWWW',
      'WEFFFFFFFFW',
      'WWWWW     W',
      'WEEEW     W',
      'WWWWWWWWWWW',
    ]
  },
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWW',
      'WX     P  W',
      'WWWWWWWWWWW',
    ]
  },
  {
    width: 64,
    height: 64,
    level: [
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      "WEEEEFFFEFFFEEEEEFEEEEEEFW",
      "WEFFFFFEFEFFEFEFEFEFFFFFFW",
      "WEFEEFFEEEFFEFEFEFEEEEEEFW",
      "WEFFEFFEFEFFEFEFEFEFFFFFFW",
      "WEEEEFFEFEFFEFEFEFEEEEEEFW",
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      'W            P           W',
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WEEEFFEFFEEEFEEEFEEEFEEFFW',
      'WEFEFEFEFEFFFEFFFEFFFEFEFW',
      'WEEEFEEEFEEEFEEEFEEEFEFFEW',
      'WEFFFEFEFFFEFFFEFEFFFEFEFW',
      'WEFFFEFEFEEEFEEEFEEEFEEFFW',
      'WWWWWWWWWWWWWWWWWWWWWWWWWW'
    ]
  }
];